export * from './Carrusel/InfoIcons/Info';
export * from './Carrusel';
export * from './Head';
export * from './HomePage/Avatar/Avatar';
export * from './HomePage/Footer/Footer';
export * from './HomePage/InfoBlock/Personalnfo';
export * from './HomePage/Navbar/ListNav/MapMenu';
export { default as NavBar } from './HomePage/Navbar/NavBar';
export * from './HomePage/Projects/InfoProyect/InfoProyect';
export * from './HomePage/Projects/ListProyects';
export * from './index';
